### ISSUE TITLE
Ceylon IDE does not build with Maven 3.1

### ISSUE THREAD

**Issue by luolong** [ceylon/ceylon-ide-eclipse#737]
I recently upgraded to Maven 3.1

As I tried to build the ceylon-ide-eclipse project today using `mvm clean install`, I got this stack trace from Maven:

```
---------------------------------------------------
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
    at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:92)
    at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.getDependencyMetadata(P2TargetPlatformResolver.java:144)
    at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.setupProjects(P2TargetPlatformResolver.java:126)
    at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.setupProject(DefaultTychoDependencyResolver.java:87)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:77)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:271)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

Quick Google search directed me to this StackOverflow question: [Maven NatTable clean+install failure](http://stackoverflow.com/questions/18058419/maven-nattable-cleaninstall-failure).

It appears that Maven 3.1 introduced some backwards incompatible changes in the public Aether API that broke many of the plugins including Tycho. Current workaround is to either use version `0.18.1` of the Tycho plug-in with Maven 3.1 or downgrade maven to 3.0.

**Comment by bjansen** [comment]
I think this one has been fixed for a long time, I'm currently building the plugin with Maven 3.3.9 without any error.
